### PR TITLE
Bump to 0.15.6

### PR DESCRIPTION
**Pull request by ringsaturn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ringsaturn** [comment]
I try to copy codes from https://github.com/conda-forge/tzfpy-feedstock/pull/12/commits/c654935edf84f04940455b23bb7e88f2311b4694 but still failed on lint issues.

**Comment by ringsaturn** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
I'm fixing the linting issues in #15. I think the best strategy is to merge that once it finishes than add the `bot-rerun` label to #12

**Comment by synapticarbors** [comment]
closed by #15 and #16

**Comment by ringsaturn** [comment]
Thank you so much for helping!

**Comment by sanjeetsinghpr** [comment]
you are doing well

**Pull request closed without merging**
